resources:
  - name:       Git
    type:       GitRepo
    configuration:
      gitProvider:  gitsource
      path:         shahiinn/project-examples     

pipelines:
  - name: pipe1
    steps:
    - name: try1
      type: Bash
            
      execution:
          onExecute:
            - echo "hey, I am running"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong."
          onComplete: #always
            - echo "Cleaning up some stuff."
          onCancel:
            - echo "Someone cancelled the job."
